[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.77"
quote = "1.0.37"
lazy_static = { version = "1.5.0", features = [] }
once_cell = "1.20.0"
